# -*- coding: utf-8 -*-
"""Schoold admininstration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Y8tzmruS5tOu_S3T1akTCMWtstwVZiY
"""

import csv
list1=[]
with open("SchoolAdmin.csv","w+") as file:
    wr=csv.writer(file)
    if file.tell()==0:
        wr.writerow(["SNO","NAME","ID","NUMBER","EMAIL"])  
    d=0
    def sch(h):
        while True:  
            lits1=input("ENTER - 'STUDENT NAME' 'ID' 'CONTACT NUMBER' 'EMAIL ID'")
            a=lits1.split()
            print("CHECK DEATILS:",a)
            i=a[0]
            j=a[1]
            k=a[2]
            l=a[3]
            b=input("ENTER 'YES' TO CHANGE THE DEATILS OR ENTER 'N'")
            if b=="N" or b=="n":
                wr.writerow([h,i,j,k,l])
                break            
    while True:
        c=input("ENTER 'YES' TO ENTER DETAILS OR ENTER 'NO'")  
        d=d+1
        if c=="YES" or c=="yes":
            sch(d)
        else:
            break